// Danish

export const da: { [key: string]: string } = {
  no_controllers: "Ingen controllere",
  reload_ihc: "Genindlæs ihc",
  reload_ihc_title: "Home Assistant kunne ikke opdateres efter den seneste ændring. Tryk for at prøve igen.",
  reloading_ihc: "Genindlæser ihc-integrationen...",
  reload_failed: "Genindlæsningen mislykkedes - se Home Assistant-loggen",

  tab_project: "Projekt",
  tab_log: "Log",
  reload_project: "Genindlæs projekt",
  reload_project_title: "Læs projektet fra ihc-controlleren igen. Det sker af sig selv, når controlleren melder et nyt projekt, så den her er kun nødvendig, hvis den slet ikke melder en revision.",
  filter_search_placeholder: "Søg i navn, entitet eller ihc-id",
  filter_all_products: "Alle produkttyper",
  filter_count: "{0} af {1}",
  filter_clear: "Ryd søgning og filter",
  filter_no_hits: "Ingenting passer. Søgningen kigger i navnet fra projektet, ihc-id'et, og entity-id og navn i Home Assistant - og i det produkt, ressourcen sidder på.",
  loading_controller: "Henter data fra IHC-controlleren",
  log_has_details: "Detaljerne står i Home Assistant-loggen.",
  last_changed: "sidst ændret {0}",
  rooms_products: "{0} rum, {1} produkter",
  days: "dage",
  hours: "timer",

  no_log_data: "Ingen logdata",
  log_is_empty: "Loggen er tom",

  info_uptime: "Oppetid",
  info_project: "Projekt",
  info_contents: "Indhold",
  info_firmware: "Firmware",
  info_brand: "Mærke",
  info_led_dimmer_version: "Softwareversion for led-dæmper",
  info_production_date: "Produktionsdato",
  info_serial_number: "Serienummer",
  info_software_date: "Softwaredato",

  prop_resource_id: "Ressource-id:",
  badge_id_title: "IHC-ressource-id'et. Det er dét den manuelle opsætning og IHC Visual peger på.",
  prop_copy_title: "Kopiér ressource-id'et til udklipsholderen",
  prop_type: "Type:",
  prop_value: "Værdi lige nu:",
  prop_value_title: "Værdien i ihc-controlleren lige nu. Knapperne ved siden af skriver til controlleren, så de tænder og slukker den rigtige udgang.",
  prop_entity: "Entitet:",
  sec_ihc: "I IHC",
  sec_hass: "I Home Assistant",
  sec_actions: "Handlinger",
  prop_close: "Luk",
  prop_display_name: "Home Assistant-navn:",
  prop_display_name_title: "Det navn Home Assistant viser. Det virker med det samme - ingen genstart - og det bliver bevaret, når ihc-integrationen genindlæses.",
  name_placeholder: "(navnet fra ihc-opsætningen)",
  not_in_hass: "Ressourcen er ikke en entitet i Home Assistant endnu.",
  automatic_help: "Entiteten kommer fra ihc-opsætningen selv og ikke fra en manuel opsætning, så der er ikke noget at fjerne her.",
  rename_edit_id: "Ret entity-id",
  rename_saved: "Gemt",
  rename_cancel: "Fortryd",
  rename_saving: "Gemmer...",
  entity_id_warning: "Alt der peger på det gamle entity-id holder op med at virke: automatiseringer, scripts, scener, dashboards, skabeloner - og alt uden for Home Assistant. Dette panel kan ikke fortælle dig hvad det er. Det kan Home Assistants egen entitetsdialog under Indstillinger, Enheder og tjenester, Entiteter.",
  rename_no_entity: "Der er ingen entitet at omdøbe.",
  rename_not_in_registry: "Entiteten står ikke i Home Assistants entitetsregister og kan derfor ikke omdøbes herfra.",
  rename_not_ours: "Entiteten hører ikke til denne ihc-controller.",
  rename_id_invalid: "Det er ikke et gyldigt entity-id. Det skal være domæne.navn med små bogstaver og understreg i stedet for mellemrum.",
  rename_id_domain: "Delen før punktummet siger hvad slags entitet det er, og den kan ikke ændres ved at omdøbe.",
  rename_id_taken: "Det entity-id er allerede i brug.",
  rename_failed: "Omdøbningen mislykkedes - se Home Assistant-loggen",
  binary_sensor_help: "Sensoren er on mens knappen holdes nede og off når den slippes. Et kort tryk og slippet kan bruges direkte som udløsere, og et langt tryk er den samme udløser med en varighed på. Et dobbeltklik skal bygges: det første tryk må vente og se om der kommer et mere, så hvert enkelt tryk bliver forsinket lige så længe som det vindue varer.",
  prop_product: "Produkt:",
  prop_product_type: "Produkttype:",
  prop_ihc_icon: "ikon {0}",
  prop_product_no_icon: "intet eget ikon",
  pick_icon_title: "Vælg et ikon til dette rum",
  dlg_icon_title: "Ikon til {0}",
  dlg_icon_hint: "Et hvilket som helst material-ikon, f.eks. mdi:sofa eller mdi:washing-machine. Ikonet ved siden af feltet viser hvordan det ser ud. Valget gemmes i Home Assistant, så rummene ser ens ud i alle browsere.",
  dlg_icon_clear: "Standard",
  icon_save_failed: "Ikonet kunne ikke gemmes - se Home Assistant-loggen",
  value_on: "til",
  value_off: "fra",
  value_toggle: "skift",
  value_on_title: "Sæt værdien til Til (true)",
  value_off_title: "Sæt værdien til Fra (false)",
  value_toggle_title: "Skift værdien",
  remove_manual: "Fjern manuel opsætning",
  manual_help: "Ressourcen er sat op manuelt. Knappen ovenfor tager den ud af Home Assistant igen - sammen med dens område og labels.",
  pending_removal_help: "Den manuelle opsætning er fjernet. Entiteten findes stadig, indtil Home Assistant har genindlæst ihc-integrationen, men ressource-id'et er frit og kan tilføjes igen med det samme.",
  working_update: "Opdaterer Home Assistant...",
  not_updated_yet: "Sat op, men Home Assistant er ikke opdateret endnu. Knappen øverst prøver igen.",
  add_already_set_up: "Ressourcen er allerede sat op i Home Assistant.",
  change_failed: "Ændringen kunne ikke laves - se Home Assistant-loggen",
  remove_dlg_title: "Fjern fra Home Assistant?",
  remove_dlg_text: "{0} slettes fra Home Assistant sammen med sit område og sine labels. Tilføjes ressourcen igen, bliver den en ny entitet.",
  remove_dlg_checking: "Ser efter hvad der bruger den...",
  remove_dlg_used: "Det her bruger den og holder op med at virke:",
  remove_dlg_unused: "Ingen automatiseringer, scripts, scener, grupper eller dashboards bruger den.",
  remove_dlg_not_checked: "Skabeloner og andre integrationer, fx Alarmo, er ikke tjekket.",
  remove_dlg_lookup_failed: "Det kunne ikke slås op, hvad der bruger den.",
  remove_dlg_ok: "Fjern",
  used_automation: "Automatiseringer",
  used_script: "Scripts",
  used_scene: "Scener",
  used_group: "Grupper",
  used_person: "Personer",
  used_dashboard: "Dashboards",
  suggest_product: "Fremhævet ud fra produkttypen: {0}",
  suggest_light_level: "Fremhævet fordi ressourcen er et lysniveau.",
  add_binary_sensor_button: "Binær sensor",
  add_light_button: "Lys",
  add_sensor_button: "Sensor",
  add_switch_button: "Kontakt",
  add_help: "Klik på en af knapperne for at sætte dette ihc-ressource-id op som en entitet i Home Assistant. Bemærk: det er en manuel opsætning, og du bør vide, hvad du gør. At noget kan tilføjes, betyder ikke, at det giver mening.",
  sec_add: "Tilføj til Home Assistant",
  not_in_hass_how: "Vælg under »Tilføj til Home Assistant« hvad den skal være. Du bliver spurgt om et navn, og entity-id'et bygges ud fra det.",
  add_binary_sensor_help: "En sensor der er on eller off. Den rigtige til en knap eller en kontakt: on mens den holdes nede, off når den slippes. Den læser kun.",
  add_light_help: "En lampe der kan tændes og slukkes fra Home Assistant - og dæmpes, hvis ressourcen er et lysniveau.",
  add_switch_help: "Noget der kan tændes og slukkes fra Home Assistant. Til en udgang der ikke er en lampe: en stikkontakt, en sirene, et relæ.",
  add_sensor_help: "En måling - et tal, en temperatur, et klokkeslæt. Den læser kun.",
  add_writes_input: "Ressourcen er en indgang, så at tænde den skriver til controlleren: den fortæller, at knappen er trykket.",

  dlg_binary_sensor_title: "Tilføj en binær sensor",
  dlg_light_title: "Tilføj et lys",
  dlg_switch_title: "Tilføj en kontakt",
  dlg_sensor_title: "Tilføj en sensor",
  dlg_resource_id: "IHC-ressource-id: {0}",
  dlg_name: "Navn",
  dlg_entity_id_becomes: "Entity-id: {0}",
  dlg_inverted: "Inverteret",
  dlg_type: "Type",
  dlg_unit: "Måleenhed (valgfri)",
  dlg_ok: "Ok",
  dlg_cancel: "Annullér",
  dlg_name_required: "Du skal angive et navn",
};
