// English. This is the master list - every other language is a translation of
// the values here, with the same keys.

export const en: { [key: string]: string } = {
  // panel
  no_controllers: "No controllers",
  reload_ihc: "Reload ihc",
  reload_ihc_title: "Home Assistant could not be updated after the last change. Press to try again.",
  reloading_ihc: "Reloading the ihc integration...",
  reload_failed: "The reload failed - see the Home Assistant log",

  // the controller card and its tabs
  tab_project: "Project",
  tab_log: "Log",
  reload_project: "Reload project",
  reload_project_title: "Read the project from the ihc controller again. It is read again by itself when the controller reports a new one, so this is only needed if it reports no revision at all.",
  filter_search_placeholder: "Search name, entity or ihc id",
  filter_all_products: "All product types",
  filter_count: "{0} of {1}",
  filter_clear: "Clear the search and the filter",
  filter_no_hits: "Nothing matches. The search looks through the name in the project, the ihc id, and the entity id and name in Home Assistant - and through the product the resource sits on.",
  loading_controller: "Loading IHC Controller data",
  log_has_details: "The Home Assistant log has the details.",
  last_changed: "last changed {0}",
  rooms_products: "{0} rooms, {1} products",
  days: "days",
  hours: "hours",

  // the log tab
  no_log_data: "No log data",
  log_is_empty: "Log is empty",

  // the info tab
  info_uptime: "Uptime",
  info_project: "Project",
  info_contents: "Contents",
  info_firmware: "Firmware",
  info_brand: "Brand",
  info_led_dimmer_version: "Led dimmer software version",
  info_production_date: "Production date",
  info_serial_number: "Serial number",
  info_software_date: "Software date",

  // the properties along the bottom
  prop_resource_id: "Resource id:",
  badge_id_title: "The ihc resource id. This is what the manual setup and IHC Visual point at.",
  prop_copy_title: "Copy the resource id to the clipboard",
  prop_type: "Type:",
  prop_value: "Value now:",
  prop_value_title: "The value in the ihc controller right now. The buttons beside it write to the controller, so they switch the real output.",
  prop_entity: "Entity:",
  sec_ihc: "In IHC",
  sec_hass: "In Home Assistant",
  sec_actions: "Actions",
  prop_close: "Close",
  prop_display_name: "Home Assistant name:",
  prop_display_name_title: "The name Home Assistant shows. It takes effect right away - no restart - and it is kept when the ihc integration is reloaded.",
  name_placeholder: "(the name from the ihc setup)",
  not_in_hass: "This resource is not an entity in Home Assistant yet.",
  automatic_help: "This entity comes from the ihc setup itself rather than from a manual setup, so there is nothing to remove here.",
  rename_edit_id: "Change the entity id",
  rename_saved: "Saved",
  rename_cancel: "Cancel",
  rename_saving: "Saving...",
  entity_id_warning: "Everything that points at the old entity id stops working: automations, scripts, scenes, dashboards, templates - and anything outside Home Assistant. This panel cannot tell you what they are. Home Assistant's own entity dialog can, under Settings, Devices and services, Entities.",
  rename_no_entity: "There is no entity to rename.",
  rename_not_in_registry: "This entity is not in Home Assistant's entity registry, so it cannot be renamed here.",
  rename_not_ours: "This entity does not belong to this ihc controller.",
  rename_id_invalid: "That is not a valid entity id. It has to be domain.name, in small letters, with underscores instead of spaces.",
  rename_id_domain: "The part before the dot says what kind of entity it is, and that cannot be changed by renaming.",
  rename_id_taken: "That entity id is already in use.",
  rename_failed: "The rename failed - see the Home Assistant log",
  binary_sensor_help: "The sensor is on while the button is held and off when it is let go. A short press and the release can be used as triggers on their own, and a long press is the same trigger with a duration on it. A double click has to be built: the first press has to wait and see whether a second one follows, so every single press is delayed by as long as that window lasts.",
  prop_product: "Product:",
  prop_product_type: "Product type:",
  prop_ihc_icon: "icon {0}",
  prop_product_no_icon: "no icon of its own",
  pick_icon_title: "Choose an icon for this room",
  dlg_icon_title: "Icon for {0}",
  dlg_icon_hint: "Any material icon, for example mdi:sofa or mdi:washing-machine. The icon beside the field shows what it looks like. The choice is kept by Home Assistant, so the rooms look the same in every browser.",
  dlg_icon_clear: "Default",
  icon_save_failed: "The icon could not be saved - see the Home Assistant log",
  value_on: "on",
  value_off: "off",
  value_toggle: "toggle",
  value_on_title: "Set the value to On (true)",
  value_off_title: "Set the value to Off (false)",
  value_toggle_title: "Toggle the value",
  remove_manual: "Remove manual setup",
  manual_help: "This resource is set up manually. The button above takes it out of Home Assistant again - together with its area and labels.",
  pending_removal_help: "The manual setup has been removed. The entity is still there until Home Assistant has reloaded the ihc integration, but the resource id is free and can be added again right away.",
  working_update: "Updating Home Assistant...",
  not_updated_yet: "Set up, but Home Assistant has not been updated yet. The button at the top tries again.",
  add_already_set_up: "This resource is already set up in Home Assistant.",
  change_failed: "The change could not be made - see the Home Assistant log",
  remove_dlg_title: "Remove from Home Assistant?",
  remove_dlg_text: "{0} is deleted from Home Assistant together with its area and labels. If the resource is added again, it becomes a new entity.",
  remove_dlg_checking: "Looking for what uses it...",
  remove_dlg_used: "These use it and will stop working:",
  remove_dlg_unused: "No automations, scripts, scenes, groups or dashboards use it.",
  remove_dlg_not_checked: "Templates and other integrations, such as Alarmo, are not checked.",
  remove_dlg_lookup_failed: "What uses it could not be looked up.",
  remove_dlg_ok: "Remove",
  used_automation: "Automations",
  used_script: "Scripts",
  used_scene: "Scenes",
  used_group: "Groups",
  used_person: "People",
  used_dashboard: "Dashboards",
  suggest_product: "Highlighted from the product type: {0}",
  suggest_light_level: "Highlighted because the resource is a light level.",
  add_binary_sensor_button: "Binary sensor",
  add_light_button: "Light",
  add_sensor_button: "Sensor",
  add_switch_button: "Switch",
  add_help: "To make a manual setup of this ihc resource id as a Home Assistant entity, click one of the buttons. Note: this is a manual setup. You should know what you are doing. Just because it is possible to add something, does not mean it make sense.",
  sec_add: "Add to Home Assistant",
  not_in_hass_how: "Pick what it should be under »Add to Home Assistant«. You are asked for a name, and the entity id is built from it.",
  add_binary_sensor_help: "A sensor that is on or off. The right one for a button or a contact: on while it is held, off when it is let go. It only reads.",
  add_light_help: "A lamp that can be turned on and off from Home Assistant - and dimmed, if the resource is a light level.",
  add_switch_help: "Something that can be turned on and off from Home Assistant. For an output that is not a lamp: a socket, a siren, a relay.",
  add_sensor_help: "A reading - a number, a temperature, a time. It only reads.",
  add_writes_input: "This resource is an input, so turning it on writes to the controller: it says the button has been pressed.",

  // the dialogs
  dlg_binary_sensor_title: "Add a binary sensor",
  dlg_light_title: "Add a light",
  dlg_switch_title: "Add a switch",
  dlg_sensor_title: "Add a sensor",
  dlg_resource_id: "IHC resource id: {0}",
  dlg_name: "Name",
  dlg_entity_id_becomes: "Entity id: {0}",
  dlg_inverted: "Inverted",
  dlg_type: "Type",
  dlg_unit: "Unit of measurement (optional)",
  dlg_ok: "Ok",
  dlg_cancel: "Cancel",
  dlg_name_required: "You must specify a name",
};
