// Estonian

export const et: { [key: string]: string } = {
  no_controllers: "Kontrollereid pole",
  reload_ihc: "Laadi ihc uuesti",
  reload_ihc_title: "Home Assistanti ei õnnestunud pärast viimast muudatust uuendada. Vajuta, et uuesti proovida.",
  reloading_ihc: "Laadin ihc integratsiooni uuesti...",
  reload_failed: "Uuesti laadimine ebaõnnestus - vaata Home Assistanti logi",

  tab_project: "Projekt",
  tab_log: "Logi",
  reload_project: "Laadi projekt uuesti",
  reload_project_title: "Loe projekt ihc kontrollerist uuesti. See loetakse ise uuesti, kui kontroller teatab uuest projektist, nii et seda on vaja ainult siis, kui ta üldse revisjoni ei teata.",
  filter_search_placeholder: "Otsi nimest, olemist või ihc id-st",
  filter_all_products: "Kõik tootetüübid",
  filter_count: "{0} / {1}",
  filter_clear: "Tühjenda otsing ja filter",
  filter_no_hits: "Midagi ei sobi. Otsing vaatab projekti nime, ihc id-d ning Home Assistanti olemi id-d ja nime - ja toodet, mille küljes ressurss on.",
  loading_controller: "Laadin IHC kontrolleri andmeid",
  log_has_details: "Üksikasjad on Home Assistanti logis.",
  last_changed: "viimati muudetud {0}",
  rooms_products: "{0} ruumi, {1} toodet",
  days: "päeva",
  hours: "tundi",

  no_log_data: "Logiandmeid pole",
  log_is_empty: "Logi on tühi",

  info_uptime: "Tööaeg",
  info_project: "Projekt",
  info_contents: "Sisu",
  info_firmware: "Püsivara",
  info_brand: "Kaubamärk",
  info_led_dimmer_version: "Led-hämardi tarkvara versioon",
  info_production_date: "Tootmiskuupäev",
  info_serial_number: "Seerianumber",
  info_software_date: "Tarkvara kuupäev",

  prop_resource_id: "Ressursi id:",
  badge_id_title: "IHC ressursi id. Sellele viitavad käsitsi seadistus ja IHC Visual.",
  prop_copy_title: "Kopeeri ressursi id lõikelauale",
  prop_type: "Tüüp:",
  prop_value: "Väärtus praegu:",
  prop_value_title: "Väärtus ihc kontrolleris praegu. Kõrvalolevad nupud kirjutavad kontrollerisse, seega lülitavad need tegelikku väljundit.",
  prop_entity: "Olem:",
  sec_ihc: "IHC-s",
  sec_hass: "Home Assistantis",
  sec_actions: "Tegevused",
  prop_close: "Sulge",
  prop_display_name: "Nimi Home Assistantis:",
  prop_display_name_title: "Nimi, mida Home Assistant näitab. See jõustub kohe - ilma taaskäivituseta - ja säilib, kui ihc integratsioon uuesti laaditakse.",
  name_placeholder: "(nimi ihc seadistusest)",
  not_in_hass: "See ressurss ei ole veel Home Assistanti olem.",
  automatic_help: "Olem tuleb ihc seadistusest endast, mitte käsitsi seadistusest, seega siin pole midagi eemaldada.",
  rename_edit_id: "Muuda olemi id-d",
  rename_saved: "Salvestatud",
  rename_cancel: "Loobu",
  rename_saving: "Salvestan...",
  entity_id_warning: "Kõik, mis viitab vanale olemi id-le, lakkab töötamast: automaatikad, skriptid, stseenid, töölauad, mallid - ja kõik väljaspool Home Assistanti. See paneel ei oska öelda, mis need on. Home Assistanti enda olemi dialoog oskab, jaotises Seaded, Seadmed ja teenused, Olemid.",
  rename_no_entity: "Pole olemit, mida ümber nimetada.",
  rename_not_in_registry: "Seda olemit pole Home Assistanti olemiregistris, seega ei saa seda siit ümber nimetada.",
  rename_not_ours: "See olem ei kuulu sellele ihc kontrollerile.",
  rename_id_invalid: "See ei ole kehtiv olemi id. See peab olema domeen.nimi väiketähtedega ja alakriipsudega tühikute asemel.",
  rename_id_domain: "Punkti ees olev osa ütleb, mis tüüpi olem see on, ja seda ei saa ümbernimetamisega muuta.",
  rename_id_taken: "See olemi id on juba kasutusel.",
  rename_failed: "Ümbernimetamine ebaõnnestus - vaata Home Assistanti logi",
  binary_sensor_help: "Andur on on, kuni nuppu hoitakse all, ja off, kui see lahti lastakse. Lühikest vajutust ja lahtilaskmist saab kasutada otse päästikutena ning pikk vajutus on sama päästik kestusega. Topeltklikk tuleb ehitada: esimene vajutus peab ootama, kas tuleb teine, seega iga üksik vajutus viibib sama kaua kui see aken kestab.",
  prop_product: "Toode:",
  prop_product_type: "Tootetüüp:",
  prop_ihc_icon: "ikoon {0}",
  prop_product_no_icon: "puudub oma ikoon",
  pick_icon_title: "Vali sellele ruumile ikoon",
  dlg_icon_title: "Ruumi {0} ikoon",
  dlg_icon_hint: "Ükskõik milline material-ikoon, näiteks mdi:sofa või mdi:washing-machine. Välja kõrval olev ikoon näitab, milline see välja näeb. Valik salvestatakse Home Assistanti, nii et ruumid näevad kõigis brauserites ühesugused välja.",
  dlg_icon_clear: "Vaikimisi",
  icon_save_failed: "Ikooni ei õnnestunud salvestada - vaata Home Assistanti logi",
  value_on: "sees",
  value_off: "väljas",
  value_toggle: "lülita",
  value_on_title: "Määra väärtuseks Sees (true)",
  value_off_title: "Määra väärtuseks Väljas (false)",
  value_toggle_title: "Lülita väärtust",
  remove_manual: "Eemalda käsitsi seadistus",
  manual_help: "See ressurss on seadistatud käsitsi. Ülalolev nupp eemaldab selle uuesti Home Assistantist - koos selle ala ja siltidega.",
  pending_removal_help: "Käsitsi tehtud seadistus on eemaldatud. Olem on alles seni, kuni Home Assistant on ihc integratsiooni uuesti laadinud, kuid ressursi id on vaba ja selle saab kohe uuesti lisada.",
  working_update: "Uuendan Home Assistanti...",
  not_updated_yet: "Seadistatud, kuid Home Assistant pole veel uuendatud. Ülal olev nupp proovib uuesti.",
  add_already_set_up: "See ressurss on juba Home Assistantis seadistatud.",
  change_failed: "Muudatust ei saanud teha - vaata Home Assistanti logi",
  remove_dlg_title: "Eemaldada Home Assistantist?",
  remove_dlg_text: "{0} kustutatakse Home Assistantist koos selle ala ja siltidega. Kui ressurss uuesti lisatakse, saab sellest uus olem.",
  remove_dlg_checking: "Otsin, mis seda kasutab...",
  remove_dlg_used: "Need kasutavad seda ja lakkavad töötamast:",
  remove_dlg_unused: "Ükski automaatika, skript, stseen, grupp ega töölaud ei kasuta seda.",
  remove_dlg_not_checked: "Malle ja teisi integratsioone, näiteks Alarmot, ei kontrollitud.",
  remove_dlg_lookup_failed: "Ei õnnestunud välja selgitada, mis seda kasutab.",
  remove_dlg_ok: "Eemalda",
  used_automation: "Automaatikad",
  used_script: "Skriptid",
  used_scene: "Stseenid",
  used_group: "Grupid",
  used_person: "Isikud",
  used_dashboard: "Töölauad",
  add_binary_sensor_button: "Binaarne andur",
  add_light_button: "Valgusti",
  add_sensor_button: "Andur",
  add_switch_button: "Lüliti",
  add_help: "Selle ihc ressursi id seadistamiseks Home Assistanti olemiks klõpsa ühel nuppudest. Pane tähele: see on käsitsi seadistus ja sa peaksid teadma, mida teed. See, et midagi on võimalik lisada, ei tähenda, et sellel oleks mõtet.",
  sec_add: "Lisa Home Assistanti",
  not_in_hass_how: "Vali jaotises »Lisa Home Assistanti«, mis see olema peaks. Sinult küsitakse nime ja olemi id koostatakse selle põhjal.",
  add_binary_sensor_help: "Andur mis on on või off. Õige valik nupule või kontaktile: on kuni seda all hoitakse, off kui lahti lastakse. See ainult loeb.",
  add_light_help: "Valgusti mida saab Home Assistantist sisse ja välja lülitada - ja hämardada, kui ressurss on valgustase.",
  add_switch_help: "Miski mida saab Home Assistantist sisse ja välja lülitada. Väljundile mis ei ole valgusti: pistikupesa, sireen, relee.",
  add_sensor_help: "Näit - arv, temperatuur, kellaaeg. See ainult loeb.",
  add_writes_input: "Ressurss on sisend, seega selle sisselülitamine kirjutab kontrollerisse: see ütleb, et nuppu on vajutatud.",

  dlg_binary_sensor_title: "Lisa binaarne andur",
  dlg_light_title: "Lisa valgusti",
  dlg_switch_title: "Lisa lüliti",
  dlg_sensor_title: "Lisa andur",
  dlg_resource_id: "IHC ressursi id: {0}",
  dlg_name: "Nimi",
  dlg_entity_id_becomes: "Olemi id: {0}",
  dlg_inverted: "Inverteeritud",
  dlg_type: "Tüüp",
  dlg_unit: "Mõõtühik (valikuline)",
  dlg_ok: "Ok",
  dlg_cancel: "Loobu",
  dlg_name_required: "Pead sisestama nime",
};
