// Finnish

export const fi: { [key: string]: string } = {
  no_controllers: "Ei ohjaimia",
  reload_ihc: "Lataa ihc uudelleen",
  reload_ihc_title: "Home Assistantia ei voitu päivittää viimeisimmän muutoksen jälkeen. Paina yrittääksesi uudelleen.",
  reloading_ihc: "Ladataan ihc-integraatiota uudelleen...",
  reload_failed: "Uudelleenlataus epäonnistui - katso Home Assistant -loki",

  tab_project: "Projekti",
  tab_log: "Loki",
  filter_search_placeholder: "Hae nimestä, entiteetistä tai ihc-tunnuksesta",
  filter_all_products: "Kaikki tuotetyypit",
  filter_count: "{0} / {1}",
  filter_clear: "Tyhjennä haku ja suodatin",
  filter_no_hits: "Mikään ei täsmää. Haku katsoo projektin nimen, ihc-tunnuksen sekä Home Assistantin entiteettitunnuksen ja nimen - ja tuotteen, jossa resurssi on.",
  loading_controller: "Haetaan tietoja IHC-ohjaimelta",
  log_has_details: "Tarkemmat tiedot ovat Home Assistant -lokissa.",
  last_changed: "muutettu viimeksi {0}",
  rooms_products: "{0} huonetta, {1} tuotetta",
  days: "päivää",
  hours: "tuntia",

  no_log_data: "Ei lokitietoja",
  log_is_empty: "Loki on tyhjä",

  info_uptime: "Käyttöaika",
  info_project: "Projekti",
  info_contents: "Sisältö",
  info_firmware: "Laiteohjelmisto",
  info_brand: "Merkki",
  info_led_dimmer_version: "Led-himmentimen ohjelmistoversio",
  info_production_date: "Valmistuspäivä",
  info_serial_number: "Sarjanumero",
  info_software_date: "Ohjelmiston päiväys",

  prop_resource_id: "Resurssitunnus:",
  badge_id_title: "IHC-resurssitunnus. Tähän manuaalinen määritys ja IHC Visual osoittavat.",
  prop_copy_title: "Kopioi resurssitunnus leikepöydälle",
  prop_type: "Tyyppi:",
  prop_value: "Arvo nyt:",
  prop_value_title: "Arvo ihc-ohjaimessa juuri nyt. Viereiset painikkeet kirjoittavat ohjaimeen, joten ne kytkevät todellisen lähdön.",
  prop_entity: "Entiteetti:",
  sec_ihc: "IHC:ssä",
  sec_hass: "Home Assistantissa",
  sec_actions: "Toiminnot",
  prop_close: "Sulje",
  prop_display_name: "Nimi Home Assistantissa:",
  prop_display_name_title: "Nimi, jonka Home Assistant näyttää. Se tulee voimaan heti - ei uudelleenkäynnistystä - ja säilyy, kun ihc-integraatio ladataan uudelleen.",
  name_placeholder: "(nimi ihc-määrityksestä)",
  not_in_hass: "Tämä resurssi ei ole vielä Home Assistantin entiteetti.",
  automatic_help: "Entiteetti tulee itse ihc-määrityksestä eikä manuaalisesta määrityksestä, joten täällä ei ole mitään poistettavaa.",
  rename_edit_id: "Muuta entiteetin tunnusta",
  rename_saved: "Tallennettu",
  rename_cancel: "Peruuta",
  rename_saving: "Tallennetaan...",
  entity_id_warning: "Kaikki, mikä osoittaa vanhaan entiteettitunnukseen, lakkaa toimimasta: automaatiot, skriptit, näkymät, kojelaudat, mallit - ja kaikki Home Assistantin ulkopuolella. Tämä paneeli ei voi kertoa, mitä ne ovat. Home Assistantin oma entiteetti-ikkuna voi, kohdassa Asetukset, Laitteet ja palvelut, Entiteetit.",
  rename_no_entity: "Nimettävää entiteettiä ei ole.",
  rename_not_in_registry: "Tämä entiteetti ei ole Home Assistantin entiteettirekisterissä, joten sitä ei voi nimeä täältä.",
  rename_not_ours: "Tämä entiteetti ei kuulu tälle ihc-ohjaimelle.",
  rename_id_invalid: "Tämä ei ole kelvollinen entiteettitunnus. Sen on oltava muotoa alue.nimi pienillä kirjaimilla ja alaviivoilla välilyöntien sijaan.",
  rename_id_domain: "Pisteen edellä oleva osa kertoo, minkälainen entiteetti on, eikä sitä voi muuttaa nimeämällä.",
  rename_id_taken: "Tämä entiteettitunnus on jo käytössä.",
  rename_failed: "Nimeäminen epäonnistui - katso Home Assistantin loki",
  binary_sensor_help: "Anturi on on, kun painiketta pidetään pohjassa, ja off, kun se vapautetaan. Lyhyttä painallusta ja vapautusta voi käyttää suoraan liipaisimina, ja pitkä painallus on sama liipaisin kestolla. Kaksoisnapsautus on rakennettava: ensimmäisen painalluksen on odotettava, tuleeko toinen, joten jokainen yksittäinen painallus viivästyy yhtä kauan kuin ikkuna kestää.",
  prop_product: "Tuote:",
  prop_product_type: "Tuotetyyppi:",
  prop_ihc_icon: "kuvake {0}",
  prop_product_no_icon: "ei omaa kuvaketta",
  pick_icon_title: "Valitse tälle huoneelle kuvake",
  dlg_icon_title: "Huoneen {0} kuvake",
  dlg_icon_hint: "Mikä tahansa material-kuvake, esimerkiksi mdi:sofa tai mdi:washing-machine. Kentän vieressä oleva kuvake näyttää, miltä se näyttää. Valinta tallennetaan Home Assistantiin, joten huoneet näyttävät samalta kaikissa selaimissa.",
  dlg_icon_clear: "Oletus",
  icon_save_failed: "Kuvakkeen tallennus epäonnistui - katso Home Assistant -loki",
  value_on: "päällä",
  value_off: "pois",
  value_toggle: "vaihda",
  value_on_title: "Aseta arvoksi Päällä (true)",
  value_off_title: "Aseta arvoksi Pois (false)",
  value_toggle_title: "Vaihda arvoa",
  remove_manual: "Poista manuaalinen määritys",
  manual_help: "Tämä resurssi on määritetty manuaalisesti. Yllä oleva painike poistaa sen taas Home Assistantista - yhdessä sen alueen ja tunnisteiden kanssa.",
  pending_removal_help: "Manuaalinen määritys on poistettu. Entiteetti on yhä olemassa, kunnes Home Assistant on ladannut ihc-integraation uudelleen, mutta resurssitunnus on vapaa ja se voidaan lisätä heti uudelleen.",
  working_update: "Päivitetään Home Assistantia...",
  not_updated_yet: "Määritetty, mutta Home Assistantia ei ole vielä päivitetty. Ylhäällä oleva painike yrittää uudelleen.",
  add_already_set_up: "Tämä resurssi on jo määritetty Home Assistantiin.",
  change_failed: "Muutosta ei voitu tehdä - katso Home Assistant -loki",
  remove_dlg_title: "Poistetaanko Home Assistantista?",
  remove_dlg_text: "{0} poistetaan Home Assistantista yhdessä alueensa ja tunnisteidensa kanssa. Jos resurssi lisätään uudelleen, siitä tulee uusi entiteetti.",
  remove_dlg_checking: "Etsitään, mikä käyttää sitä...",
  remove_dlg_used: "Nämä käyttävät sitä ja lakkaavat toimimasta:",
  remove_dlg_unused: "Mikään automaatio, skripti, näkymä, ryhmä tai kojelauta ei käytä sitä.",
  remove_dlg_not_checked: "Malleja ja muita integraatioita, kuten Alarmoa, ei ole tarkistettu.",
  remove_dlg_lookup_failed: "Ei voitu selvittää, mikä sitä käyttää.",
  remove_dlg_ok: "Poista",
  used_automation: "Automaatiot",
  used_script: "Skriptit",
  used_scene: "Näkymät",
  used_group: "Ryhmät",
  used_person: "Henkilöt",
  used_dashboard: "Kojelaudat",
  suggest_product: "Korostettu tuotetyypin perusteella: {0}",
  suggest_light_level: "Korostettu, koska resurssi on valotaso.",
  add_binary_sensor_button: "Binäärianturi",
  add_light_button: "Valo",
  add_sensor_button: "Anturi",
  add_switch_button: "Kytkin",
  add_help: "Määritä tämä ihc-resurssitunnus Home Assistant -entiteetiksi napsauttamalla jotakin painiketta. Huomaa: tämä on manuaalinen määritys, ja sinun on tiedettävä, mitä teet. Se, että jokin voidaan lisätä, ei tarkoita, että se olisi järkevää.",
  sec_add: "Lisää Home Assistantiin",
  not_in_hass_how: "Valitse kohdassa »Lisää Home Assistantiin«, mikä sen pitäisi olla. Sinulta kysytään nimi, ja entiteettitunnus rakennetaan siitä.",
  add_binary_sensor_help: "Anturi joka on on tai off. Oikea valinta painikkeelle tai koskettimelle: on kun sitä pidetään pohjassa, off kun se vapautetaan. Se vain lukee.",
  add_light_help: "Valo jonka voi sytyttää ja sammuttaa Home Assistantista - ja himmentää, jos resurssi on valotaso.",
  add_switch_help: "Jotain jonka voi kytkeä päälle ja pois Home Assistantista. Lähdölle joka ei ole valo: pistorasia, sireeni, rele.",
  add_sensor_help: "Lukema - luku, lämpötila, kellonaika. Se vain lukee.",
  add_writes_input: "Resurssi on tulo, joten sen kytkeminen päälle kirjoittaa ohjaimeen: se kertoo, että painiketta on painettu.",

  dlg_binary_sensor_title: "Lisää binäärianturi",
  dlg_light_title: "Lisää valo",
  dlg_switch_title: "Lisää kytkin",
  dlg_sensor_title: "Lisää anturi",
  dlg_resource_id: "IHC-resurssitunnus: {0}",
  dlg_name: "Nimi",
  dlg_entity_id_becomes: "Entiteettitunnus: {0}",
  dlg_inverted: "Käänteinen",
  dlg_type: "Tyyppi",
  dlg_unit: "Mittayksikkö (valinnainen)",
  dlg_ok: "Ok",
  dlg_cancel: "Peruuta",
  dlg_name_required: "Anna nimi",
};
