// Lithuanian

export const lt: { [key: string]: string } = {
  no_controllers: "Valdiklių nėra",
  reload_ihc: "Įkelti ihc iš naujo",
  reload_ihc_title: "Po paskutinio pakeitimo Home Assistant nepavyko atnaujinti. Paspauskite, kad bandytumėte dar kartą.",
  reloading_ihc: "Iš naujo įkeliama ihc integracija...",
  reload_failed: "Įkelti iš naujo nepavyko - žiūrėkite Home Assistant žurnalą",

  tab_project: "Projektas",
  tab_log: "Žurnalas",
  reload_project: "Įkelti projektą iš naujo",
  reload_project_title: "Iš naujo nuskaityti projektą iš ihc valdiklio. Tai įvyksta savaime, kai valdiklis praneša apie naują projektą, todėl šis reikalingas tik tada, jei jis išvis nepraneša revizijos.",
  filter_search_placeholder: "Ieškoti pavadinime, objekte arba ihc id",
  filter_all_products: "Visi gaminių tipai",
  filter_count: "{0} iš {1}",
  filter_clear: "Išvalyti paiešką ir filtrą",
  filter_no_hits: "Niekas neatitinka. Paieška žiūri į projekto pavadinimą, ihc id bei Home Assistant objekto id ir pavadinimą - ir į gaminį, prie kurio išteklius yra.",
  loading_controller: "Įkeliami IHC valdiklio duomenys",
  log_has_details: "Išsami informacija yra Home Assistant žurnale.",
  last_changed: "paskutinį kartą keista {0}",
  rooms_products: "{0} kambarių, {1} gaminių",
  days: "d.",
  hours: "val.",

  no_log_data: "Žurnalo duomenų nėra",
  log_is_empty: "Žurnalas tuščias",

  info_uptime: "Veikimo laikas",
  info_project: "Projektas",
  info_contents: "Turinys",
  info_firmware: "Programinė aparatinė įranga",
  info_brand: "Prekės ženklas",
  info_led_dimmer_version: "Led pritemdytuvo programinės įrangos versija",
  info_production_date: "Pagaminimo data",
  info_serial_number: "Serijos numeris",
  info_software_date: "Programinės įrangos data",

  prop_resource_id: "Ištekliaus id:",
  badge_id_title: "IHC ištekliaus id. Į jį rodo rankinė konfigūracija ir IHC Visual.",
  prop_copy_title: "Kopijuoti ištekliaus id į iškarpinę",
  prop_type: "Tipas:",
  prop_value: "Reikšmė dabar:",
  prop_value_title: "Reikšmė ihc valdiklyje šiuo metu. Šalia esantys mygtukai rašo į valdiklį, todėl jie perjungia tikrą išėjimą.",
  prop_entity: "Objektas:",
  sec_ihc: "IHC",
  sec_hass: "Home Assistant",
  sec_actions: "Veiksmai",
  prop_close: "Uždaryti",
  prop_display_name: "Home Assistant pavadinimas:",
  prop_display_name_title: "Pavadinimas, kurį rodo Home Assistant. Jis įsigalioja iškart - be perkrovimo - ir išlieka, kai ihc integracija perįkeliama.",
  name_placeholder: "(pavadinimas iš ihc konfigūracijos)",
  not_in_hass: "Šis išteklius dar nėra Home Assistant objektas.",
  automatic_help: "Objektas ateina iš pačios ihc konfigūracijos, o ne iš rankinės konfigūracijos, todėl čia nėra ko šalinti.",
  rename_edit_id: "Keisti objekto id",
  rename_saved: "Įrašyta",
  rename_cancel: "Atšaukti",
  rename_saving: "Įrašoma...",
  entity_id_warning: "Viskas, kas rodo į seną objekto id, nustoja veikti: automatizacijos, scenarijai, scenos, skydeliai, šablonai - ir viskas už Home Assistant ribų. Šis skydelis negali pasakyti, kas tai yra. Gali Home Assistant paties objektų dialogas, skiltyje Nustatymai, Įrenginiai ir paslaugos, Objektai.",
  rename_no_entity: "Nėra objekto, kurį būtų galima pervadinti.",
  rename_not_in_registry: "Šio objekto nėra Home Assistant objektų registre, todėl jo negalima pervadinti iš čia.",
  rename_not_ours: "Šis objektas nepriklauso šiam ihc valdikliui.",
  rename_id_invalid: "Tai nėra galiojantis objekto id. Jis turi būti sritis.pavadinimas mažosiomis raidėmis ir su pabraukimais vietoj tarpų.",
  rename_id_domain: "Dalis prieš tašką nurodo, kokio tipo objektas tai yra, ir jos pervadinant pakeisti negalima.",
  rename_id_taken: "Šis objekto id jau naudojamas.",
  rename_failed: "Pervadinti nepavyko - žiūrėkite Home Assistant žurnalą",
  binary_sensor_help: "Jutiklis yra on, kol mygtukas laikomas nuspaustas, ir off, kai jis atleidžiamas. Trumpą paspaudimą ir atleidimą galima naudoti tiesiogiai kaip aktyviklius, o ilgas paspaudimas yra tas pats aktyviklis su trukme. Dvigubas spustelėjimas turi būti sukurtas: pirmasis paspaudimas turi palaukti, ar bus antras, todėl kiekvienas atskiras paspaudimas vėluoja tiek, kiek trunka tas langas.",
  prop_product: "Gaminys:",
  prop_product_type: "Gaminio tipas:",
  prop_ihc_icon: "piktograma {0}",
  prop_product_no_icon: "neturi savos piktogramos",
  pick_icon_title: "Pasirinkite šio kambario piktogramą",
  dlg_icon_title: "Kambario {0} piktograma",
  dlg_icon_hint: "Bet kuri material piktograma, pavyzdžiui, mdi:sofa arba mdi:washing-machine. Piktograma šalia lauko rodo, kaip ji atrodo. Pasirinkimas išsaugomas Home Assistant, todėl kambariai atrodo vienodai visose naršyklėse.",
  dlg_icon_clear: "Numatytoji",
  icon_save_failed: "Piktogramos išsaugoti nepavyko - žiūrėkite Home Assistant žurnalą",
  value_on: "įjungti",
  value_off: "išjungti",
  value_toggle: "perjungti",
  value_on_title: "Nustatyti reikšmę Įjungta (true)",
  value_off_title: "Nustatyti reikšmę Išjungta (false)",
  value_toggle_title: "Perjungti reikšmę",
  remove_manual: "Pašalinti rankinę konfigūraciją",
  manual_help: "Šis išteklius nustatytas rankiniu būdu. Aukščiau esantis mygtukas vėl jį pašalina iš Home Assistant - kartu su jo sritimi ir etiketėmis.",
  pending_removal_help: "Rankinė konfigūracija pašalinta. Objektas išlieka, kol Home Assistant iš naujo įkels ihc integraciją, bet ištekliaus id yra laisvas ir jį galima iškart pridėti iš naujo.",
  working_update: "Atnaujinamas Home Assistant...",
  not_updated_yet: "Nustatyta, bet Home Assistant dar neatnaujintas. Mygtukas viršuje bando dar kartą.",
  add_already_set_up: "Šis išteklius jau nustatytas Home Assistant.",
  change_failed: "Pakeitimo atlikti nepavyko - žiūrėkite Home Assistant žurnalą",
  remove_dlg_title: "Pašalinti iš Home Assistant?",
  remove_dlg_text: "{0} ištrinamas iš Home Assistant kartu su savo sritimi ir etiketėmis. Jei išteklius bus pridėtas iš naujo, jis taps nauju objektu.",
  remove_dlg_checking: "Ieškoma, kas jį naudoja...",
  remove_dlg_used: "Šie jį naudoja ir nustos veikti:",
  remove_dlg_unused: "Jo nenaudoja jokia automatizacija, scenarijus, scena, grupė ar skydelis.",
  remove_dlg_not_checked: "Šablonai ir kitos integracijos, pavyzdžiui, Alarmo, nepatikrinti.",
  remove_dlg_lookup_failed: "Nepavyko nustatyti, kas jį naudoja.",
  remove_dlg_ok: "Pašalinti",
  used_automation: "Automatizacijos",
  used_script: "Scenarijai",
  used_scene: "Scenos",
  used_group: "Grupės",
  used_person: "Asmenys",
  used_dashboard: "Skydeliai",
  suggest_product: "Paryškinta pagal gaminio tipą: {0}",
  suggest_light_level: "Paryškinta, nes išteklius yra šviesos lygis.",
  add_binary_sensor_button: "Dvejetainis jutiklis",
  add_light_button: "Šviesa",
  add_sensor_button: "Jutiklis",
  add_switch_button: "Jungiklis",
  add_help: "Norėdami rankiniu būdu sukonfigūruoti šį ihc ištekliaus id kaip Home Assistant objektą, spustelėkite vieną iš mygtukų. Atkreipkite dėmesį: tai rankinė konfigūracija, ir turėtumėte žinoti, ką darote. Tai, kad ką nors galima pridėti, nereiškia, kad tai prasminga.",
  sec_add: "Pridėti prie Home Assistant",
  not_in_hass_how: "Skiltyje »Pridėti prie Home Assistant« pasirinkite, kuo tai turėtų būti. Būsite paprašyti pavadinimo, ir objekto id bus sukurtas iš jo.",
  add_binary_sensor_help: "Jutiklis kuris yra on arba off. Tinkamas mygtukui arba kontaktui: on kol laikomas nuspaustas, off kai atleidžiamas. Jis tik skaito.",
  add_light_help: "Šviesa kurią galima įjungti ir išjungti iš Home Assistant - ir pritemdyti, jei išteklius yra šviesos lygis.",
  add_switch_help: "Kai kas, ką galima įjungti ir išjungti iš Home Assistant. Išėjimui kuris nėra šviesa: lizdas, sirena, relė.",
  add_sensor_help: "Rodmuo - skaičius, temperatūra, laikas. Jis tik skaito.",
  add_writes_input: "Išteklius yra įėjimas, todėl jo įjungimas rašo į valdiklį: jis pasako, kad mygtukas buvo paspaustas.",

  dlg_binary_sensor_title: "Pridėti dvejetainį jutiklį",
  dlg_light_title: "Pridėti šviesą",
  dlg_switch_title: "Pridėti jungiklį",
  dlg_sensor_title: "Pridėti jutiklį",
  dlg_resource_id: "IHC ištekliaus id: {0}",
  dlg_name: "Pavadinimas",
  dlg_entity_id_becomes: "Objekto id: {0}",
  dlg_inverted: "Invertuota",
  dlg_type: "Tipas",
  dlg_unit: "Matavimo vienetas (nebūtina)",
  dlg_ok: "Gerai",
  dlg_cancel: "Atšaukti",
  dlg_name_required: "Turite nurodyti pavadinimą",
};
