// Latvian

export const lv: { [key: string]: string } = {
  no_controllers: "Nav kontrolleru",
  reload_ihc: "Pārlādēt ihc",
  reload_ihc_title: "Home Assistant nevarēja atjaunināt pēc pēdējām izmaiņām. Nospiediet, lai mēģinātu vēlreiz.",
  reloading_ihc: "Notiek ihc integrācijas pārlāde...",
  reload_failed: "Pārlāde neizdevās - skatiet Home Assistant žurnālu",

  tab_project: "Projekts",
  tab_log: "Žurnāls",
  reload_project: "Pārlādēt projektu",
  reload_project_title: "Vēlreiz nolasīt projektu no ihc kontrollera. Tas notiek pats, kad kontrolleris ziņo par jaunu projektu, tāpēc šis ir vajadzīgs tikai tad, ja tas neziņo nevienu revīziju.",
  filter_search_placeholder: "Meklēt nosaukumā, entitātē vai ihc id",
  filter_all_products: "Visi produktu tipi",
  filter_count: "{0} no {1}",
  filter_clear: "Notīrīt meklēšanu un filtru",
  filter_no_hits: "Nekas neatbilst. Meklēšana skatās projekta nosaukumā, ihc id, kā arī Home Assistant entitātes id un nosaukumā - un produktā, pie kura resurss atrodas.",
  loading_controller: "Notiek IHC kontrollera datu ielāde",
  log_has_details: "Sīkāka informācija ir Home Assistant žurnālā.",
  last_changed: "pēdējoreiz mainīts {0}",
  rooms_products: "{0} telpas, {1} produkti",
  days: "dienas",
  hours: "stundas",

  no_log_data: "Nav žurnāla datu",
  log_is_empty: "Žurnāls ir tukšs",

  info_uptime: "Darbības laiks",
  info_project: "Projekts",
  info_contents: "Saturs",
  info_firmware: "Programmaparatūra",
  info_brand: "Zīmols",
  info_led_dimmer_version: "Led regulatora programmatūras versija",
  info_production_date: "Ražošanas datums",
  info_serial_number: "Sērijas numurs",
  info_software_date: "Programmatūras datums",

  prop_resource_id: "Resursa id:",
  badge_id_title: "IHC resursa id. Uz to norāda manuālā konfigurācija un IHC Visual.",
  prop_copy_title: "Kopēt resursa id starpliktuvē",
  prop_type: "Tips:",
  prop_value: "Vērtība tagad:",
  prop_value_title: "Vērtība ihc kontrollierī šobrīd. Blakus esošās pogas raksta kontrollerī, tāpēc tās pārslēdz īsto izeju.",
  prop_entity: "Entītija:",
  sec_ihc: "IHC",
  sec_hass: "Home Assistant",
  sec_actions: "Darbības",
  prop_close: "Aizvērt",
  prop_display_name: "Home Assistant nosaukums:",
  prop_display_name_title: "Nosaukums, ko rāda Home Assistant. Tas stājas spēkā uzreiz - bez restartēšanas - un saglabājas, kad ihc integrācija tiek pārlādēta.",
  name_placeholder: "(nosaukums no ihc konfigurācijas)",
  not_in_hass: "Šis resurss vēl nav Home Assistant entitāte.",
  automatic_help: "Entitāte nāk no pašas ihc konfigurācijas, nevis no manuālas konfigurācijas, tāpēc šeit nav ko noņemt.",
  rename_edit_id: "Mainīt entitātes id",
  rename_saved: "Saglabāts",
  rename_cancel: "Atcelt",
  rename_saving: "Saglabā...",
  entity_id_warning: "Viss, kas norāda uz veco entitātes id, pārstāj darboties: automatizācijas, skripti, ainas, panelīši, veidnes - un viss ārpus Home Assistant. Šis panelis nevar pateikt, kas tie ir. To var Home Assistant paša entitāšu dialogs sadaļā Iestatījumi, Ierīces un pakalpojumi, Entitātes.",
  rename_no_entity: "Nav entitātes, ko pārdēvēt.",
  rename_not_in_registry: "Šī entitāte nav Home Assistant entitāšu reģistrā, tāpēc to nevar pārdēvēt no šejienes.",
  rename_not_ours: "Šī entitāte nepieder šim ihc kontrollierim.",
  rename_id_invalid: "Tas nav derīgs entitātes id. Tam jābūt domēns.nosaukums ar maziem burtiem un pasvītrojumiem atstarpju vietā.",
  rename_id_domain: "Daļa pirms punkta norāda, kāda veida entitāte tā ir, un to nevar mainīt pārdēvējot.",
  rename_id_taken: "Šis entitātes id jau tiek izmantots.",
  rename_failed: "Pārdēvēšana neizdevās - skatīt Home Assistant žurnālu",
  binary_sensor_help: "Sensors ir on, kamēr poga tiek turēta nospiesta, un off, kad to atlaiž. Īsu nospiešanu un atlaišanu var izmantot tieši kā aktivizētājus, un ilga nospiešana ir tas pats notikums ar ilgumu. Dubultklikšķis ir jāizveido: pirmajai nospiešanai jāgaida, vai seko otrā, tāpēc katra atsevišķā nospiešana aizkavējas tikpat ilgi, cik ilgst šis logs.",
  prop_product: "Produkts:",
  prop_product_type: "Produkta tips:",
  prop_ihc_icon: "ikona {0}",
  prop_product_no_icon: "nav savas ikonas",
  pick_icon_title: "Izvēlieties ikonu šai telpai",
  dlg_icon_title: "Telpas {0} ikona",
  dlg_icon_hint: "Jebkura material ikona, piemēram, mdi:sofa vai mdi:washing-machine. Ikona blakus laukam rāda, kā tā izskatās. Izvēle tiek saglabāta Home Assistant, tāpēc telpas izskatās vienādi visās pārlūkprogrammās.",
  dlg_icon_clear: "Noklusējums",
  icon_save_failed: "Ikonu neizdevās saglabāt - skatiet Home Assistant žurnālu",
  value_on: "ieslēgt",
  value_off: "izslēgt",
  value_toggle: "pārslēgt",
  value_on_title: "Iestatīt vērtību uz Ieslēgts (true)",
  value_off_title: "Iestatīt vērtību uz Izslēgts (false)",
  value_toggle_title: "Pārslēgt vērtību",
  remove_manual: "Noņemt manuālo konfigurāciju",
  manual_help: "Šis resurss ir iestatīts manuāli. Poga augstāk to atkal izņem no Home Assistant - kopā ar tā apgabalu un etiķetēm.",
  pending_removal_help: "Manuālā konfigurācija ir noņemta. Entītija paliek, līdz Home Assistant ir pārlādējis ihc integrāciju, bet resursa id ir brīvs un to var pievienot uzreiz no jauna.",
  working_update: "Atjaunina Home Assistant...",
  not_updated_yet: "Iestatīts, bet Home Assistant vēl nav atjaunināts. Poga augšā mēģina vēlreiz.",
  add_already_set_up: "Šis resurss jau ir iestatīts Home Assistant.",
  change_failed: "Izmaiņas nevarēja veikt - skatiet Home Assistant žurnālu",
  remove_dlg_title: "Noņemt no Home Assistant?",
  remove_dlg_text: "{0} tiek dzēsta no Home Assistant kopā ar tās apgabalu un etiķetēm. Ja resursu pievieno vēlreiz, tā kļūst par jaunu entitāti.",
  remove_dlg_checking: "Meklē, kas to izmanto...",
  remove_dlg_used: "Šie to izmanto un pārstās darboties:",
  remove_dlg_unused: "To neizmanto neviena automatizācija, skripts, aina, grupa vai panelis.",
  remove_dlg_not_checked: "Veidnes un citas integrācijas, piemēram, Alarmo, netika pārbaudītas.",
  remove_dlg_lookup_failed: "Neizdevās noskaidrot, kas to izmanto.",
  remove_dlg_ok: "Noņemt",
  used_automation: "Automatizācijas",
  used_script: "Skripti",
  used_scene: "Ainas",
  used_group: "Grupas",
  used_person: "Personas",
  used_dashboard: "Paneļi",
  suggest_product: "Izcelts pēc produkta tipa: {0}",
  suggest_light_level: "Izcelts, jo resurss ir gaismas līmenis.",
  add_binary_sensor_button: "Binārais sensors",
  add_light_button: "Gaisma",
  add_sensor_button: "Sensors",
  add_switch_button: "Slēdzis",
  add_help: "Lai manuāli konfigurētu šo ihc resursa id kā Home Assistant entītiju, noklikšķiniet uz kādas no pogām. Ņemiet vērā: šī ir manuāla konfigurācija, un jums jāzina, ko darāt. Tas, ka kaut ko var pievienot, nenozīmē, ka tam ir jēga.",
  sec_add: "Pievienot Home Assistant",
  not_in_hass_how: "Sadaļā »Pievienot Home Assistant« izvēlieties, kam tam jābūt. Jums prasīs nosaukumu, un entitātes id tiks izveidots no tā.",
  add_binary_sensor_help: "Sensors kas ir on vai off. Pareizais pogai vai kontaktam: on kamēr to tur nospiestu, off kad atlaiž. Tas tikai nolasa.",
  add_light_help: "Gaisma ko var ieslēgt un izslēgt no Home Assistant - un aptumsināt, ja resurss ir gaismas līmenis.",
  add_switch_help: "Kaut kas ko var ieslēgt un izslēgt no Home Assistant. Izejai kas nav gaisma: kontaktligzda, sirena, relejs.",
  add_sensor_help: "Rādījums - skaitlis, temperatūra, laiks. Tas tikai nolasa.",
  add_writes_input: "Resurss ir ieeja, tāpēc tā ieslēgšana raksta kontrollerī: tā pasaka, ka poga ir nospiesta.",

  dlg_binary_sensor_title: "Pievienot bināro sensoru",
  dlg_light_title: "Pievienot gaismu",
  dlg_switch_title: "Pievienot slēdzi",
  dlg_sensor_title: "Pievienot sensoru",
  dlg_resource_id: "IHC resursa id: {0}",
  dlg_name: "Nosaukums",
  dlg_entity_id_becomes: "Entitātes id: {0}",
  dlg_inverted: "Invertēts",
  dlg_type: "Tips",
  dlg_unit: "Mērvienība (neobligāti)",
  dlg_ok: "Labi",
  dlg_cancel: "Atcelt",
  dlg_name_required: "Jums jānorāda nosaukums",
};
