// Norwegian Bokmaal. Nynorsk reads this one - see the alias in index.ts.

export const nb: { [key: string]: string } = {
  no_controllers: "Ingen kontrollere",
  reload_ihc: "Last ihc på nytt",
  reload_ihc_title: "Home Assistant kunne ikke oppdateres etter den siste endringen. Trykk for å prøve igjen.",
  reloading_ihc: "Laster ihc-integrasjonen på nytt...",
  reload_failed: "Omlastingen mislyktes - se Home Assistant-loggen",

  tab_project: "Prosjekt",
  tab_log: "Logg",
  reload_project: "Last prosjektet på nytt",
  reload_project_title: "Les prosjektet fra ihc-kontrolleren på nytt. Det skjer av seg selv når kontrolleren melder et nytt prosjekt, så denne trengs bare hvis den ikke melder en revisjon i det hele tatt.",
  filter_search_placeholder: "Søk i navn, entitet eller ihc-id",
  filter_all_products: "Alle produkttyper",
  filter_count: "{0} av {1}",
  filter_clear: "Tøm søk og filter",
  filter_no_hits: "Ingenting passer. Søket ser i navnet fra prosjektet, ihc-id-en, og entitets-id og navn i Home Assistant - og i produktet ressursen sitter på.",
  loading_controller: "Henter data fra IHC-kontrolleren",
  log_has_details: "Detaljene står i Home Assistant-loggen.",
  last_changed: "sist endret {0}",
  rooms_products: "{0} rom, {1} produkter",
  days: "dager",
  hours: "timer",

  no_log_data: "Ingen loggdata",
  log_is_empty: "Loggen er tom",

  info_uptime: "Oppetid",
  info_project: "Prosjekt",
  info_contents: "Innhold",
  info_firmware: "Firmware",
  info_brand: "Merke",
  info_led_dimmer_version: "Programvareversjon for led-dimmer",
  info_production_date: "Produksjonsdato",
  info_serial_number: "Serienummer",
  info_software_date: "Programvaredato",

  prop_resource_id: "Ressurs-id:",
  badge_id_title: "IHC-ressurs-id-en. Det er den det manuelle oppsettet og IHC Visual peker på.",
  prop_copy_title: "Kopier ressurs-id-en til utklippstavlen",
  prop_type: "Type:",
  prop_value: "Verdi nå:",
  prop_value_title: "Verdien i ihc-kontrolleren akkurat nå. Knappene ved siden av skriver til kontrolleren, så de slår av og på den virkelige utgangen.",
  prop_entity: "Entitet:",
  sec_ihc: "I IHC",
  sec_hass: "I Home Assistant",
  sec_actions: "Handlinger",
  prop_close: "Lukk",
  prop_display_name: "Navn i Home Assistant:",
  prop_display_name_title: "Navnet Home Assistant viser. Det virker med en gang - ingen omstart - og beholdes når ihc-integrasjonen lastes inn på nytt.",
  name_placeholder: "(navnet fra ihc-oppsettet)",
  not_in_hass: "Ressursen er ikke en entitet i Home Assistant ennå.",
  automatic_help: "Entiteten kommer fra selve ihc-oppsettet og ikke fra et manuelt oppsett, så det er ingenting å fjerne her.",
  rename_edit_id: "Endre entitets-id",
  rename_saved: "Lagret",
  rename_cancel: "Avbryt",
  rename_saving: "Lagrer...",
  entity_id_warning: "Alt som peker på den gamle entitets-id-en slutter å virke: automasjoner, skript, scener, dashbord, maler - og alt utenfor Home Assistant. Dette panelet kan ikke si hva det er. Det kan Home Assistants egen entitetsdialog under Innstillinger, Enheter og tjenester, Entiteter.",
  rename_no_entity: "Det er ingen entitet å gi nytt navn.",
  rename_not_in_registry: "Entiteten står ikke i Home Assistants entitetsregister og kan derfor ikke gis nytt navn herfra.",
  rename_not_ours: "Entiteten hører ikke til denne ihc-kontrolleren.",
  rename_id_invalid: "Det er ikke en gyldig entitets-id. Den må være domene.navn med små bokstaver og understrek i stedet for mellomrom.",
  rename_id_domain: "Delen før punktumet sier hva slags entitet det er, og den kan ikke endres ved å gi nytt navn.",
  rename_id_taken: "Den entitets-id-en er allerede i bruk.",
  rename_failed: "Navnebyttet mislyktes - se Home Assistant-loggen",
  binary_sensor_help: "Sensoren er on mens knappen holdes nede og off når den slippes. Et kort trykk og slippet kan brukes direkte som utløsere, og et langt trykk er den samme utløseren med en varighet på. Et dobbeltklikk må bygges: det første trykket må vente og se om det kommer et til, så hvert enkelt trykk blir forsinket like lenge som det vinduet varer.",
  prop_product: "Produkt:",
  prop_product_type: "Produkttype:",
  prop_ihc_icon: "ikon {0}",
  prop_product_no_icon: "ingen egen ikon",
  pick_icon_title: "Velg et ikon for dette rommet",
  dlg_icon_title: "Ikon for {0}",
  dlg_icon_hint: "Et hvilket som helst material-ikon, for eksempel mdi:sofa eller mdi:washing-machine. Ikonet ved siden av feltet viser hvordan det ser ut. Valget lagres i Home Assistant, så rommene ser like ut i alle nettlesere.",
  dlg_icon_clear: "Standard",
  icon_save_failed: "Ikonet kunne ikke lagres - se Home Assistant-loggen",
  value_on: "på",
  value_off: "av",
  value_toggle: "veksle",
  value_on_title: "Sett verdien til På (true)",
  value_off_title: "Sett verdien til Av (false)",
  value_toggle_title: "Veksle verdien",
  remove_manual: "Fjern manuelt oppsett",
  manual_help: "Ressursen er satt opp manuelt. Knappen over tar den ut av Home Assistant igjen - sammen med området og etikettene.",
  pending_removal_help: "Det manuelle oppsettet er fjernet. Entiteten finnes fortsatt til Home Assistant har lastet ihc-integrasjonen på nytt, men ressurs-id-en er ledig og kan legges til igjen med en gang.",
  working_update: "Oppdaterer Home Assistant...",
  not_updated_yet: "Satt opp, men Home Assistant er ikke oppdatert ennå. Knappen øverst prøver igjen.",
  add_already_set_up: "Ressursen er allerede satt opp i Home Assistant.",
  change_failed: "Endringen kunne ikke gjøres - se Home Assistant-loggen",
  remove_dlg_title: "Fjerne fra Home Assistant?",
  remove_dlg_text: "{0} slettes fra Home Assistant sammen med området og etikettene sine. Legges ressursen til igjen, blir den en ny entitet.",
  remove_dlg_checking: "Ser etter hva som bruker den...",
  remove_dlg_used: "Dette bruker den og slutter å virke:",
  remove_dlg_unused: "Ingen automasjoner, skript, scener, grupper eller dashbord bruker den.",
  remove_dlg_not_checked: "Maler og andre integrasjoner, for eksempel Alarmo, er ikke sjekket.",
  remove_dlg_lookup_failed: "Det kunne ikke slås opp hva som bruker den.",
  remove_dlg_ok: "Fjern",
  used_automation: "Automasjoner",
  used_script: "Skript",
  used_scene: "Scener",
  used_group: "Grupper",
  used_person: "Personer",
  used_dashboard: "Dashbord",
  suggest_product: "Fremhevet ut fra produkttypen: {0}",
  suggest_light_level: "Fremhevet fordi ressursen er et lysnivå.",
  add_binary_sensor_button: "Binær sensor",
  add_light_button: "Lys",
  add_sensor_button: "Sensor",
  add_switch_button: "Bryter",
  add_help: "Klikk på en av knappene for å sette opp denne ihc-ressurs-id-en som en entitet i Home Assistant. Merk: dette er et manuelt oppsett, og du bør vite hva du gjør. At noe kan legges til, betyr ikke at det gir mening.",
  sec_add: "Legg til i Home Assistant",
  not_in_hass_how: "Velg under »Legg til i Home Assistant« hva den skal være. Du blir bedt om et navn, og entitets-id-en bygges ut fra det.",
  add_binary_sensor_help: "En sensor som er on eller off. Den riktige for en knapp eller en kontakt: on mens den holdes nede, off når den slippes. Den bare leser.",
  add_light_help: "En lampe som kan slås av og på fra Home Assistant - og dimmes, hvis ressursen er et lysnivå.",
  add_switch_help: "Noe som kan slås av og på fra Home Assistant. For en utgang som ikke er en lampe: en stikkontakt, en sirene, et relé.",
  add_sensor_help: "En avlesning - et tall, en temperatur, et klokkeslett. Den bare leser.",
  add_writes_input: "Ressursen er en inngang, så å slå den på skriver til kontrolleren: den sier at knappen er trykket.",

  dlg_binary_sensor_title: "Legg til en binær sensor",
  dlg_light_title: "Legg til et lys",
  dlg_switch_title: "Legg til en bryter",
  dlg_sensor_title: "Legg til en sensor",
  dlg_resource_id: "IHC-ressurs-id: {0}",
  dlg_name: "Navn",
  dlg_entity_id_becomes: "Entitets-id: {0}",
  dlg_inverted: "Invertert",
  dlg_type: "Type",
  dlg_unit: "Måleenhet (valgfritt)",
  dlg_ok: "Ok",
  dlg_cancel: "Avbryt",
  dlg_name_required: "Du må oppgi et navn",
};
