// Swedish

export const sv: { [key: string]: string } = {
  no_controllers: "Inga styrenheter",
  reload_ihc: "Läs om ihc",
  reload_ihc_title: "Home Assistant kunde inte uppdateras efter den senaste ändringen. Tryck för att försöka igen.",
  reloading_ihc: "Läser om ihc-integrationen...",
  reload_failed: "Omläsningen misslyckades - se Home Assistant-loggen",

  tab_project: "Projekt",
  tab_log: "Logg",
  reload_project: "Läs om projektet",
  reload_project_title: "Läs projektet från ihc-styrenheten igen. Det sker av sig självt när styrenheten rapporterar ett nytt projekt, så den här behövs bara om den inte rapporterar någon revision alls.",
  filter_search_placeholder: "Sök i namn, entitet eller ihc-id",
  filter_all_products: "Alla produkttyper",
  filter_count: "{0} av {1}",
  filter_clear: "Rensa sökning och filter",
  filter_no_hits: "Inget matchar. Sökningen tittar i namnet från projektet, ihc-id:t, och entitets-id och namn i Home Assistant - och i produkten som resursen sitter på.",
  loading_controller: "Hämtar data från IHC-styrenheten",
  log_has_details: "Detaljerna finns i Home Assistant-loggen.",
  last_changed: "senast ändrad {0}",
  rooms_products: "{0} rum, {1} produkter",
  days: "dagar",
  hours: "timmar",

  no_log_data: "Inga loggdata",
  log_is_empty: "Loggen är tom",

  info_uptime: "Upptid",
  info_project: "Projekt",
  info_contents: "Innehåll",
  info_firmware: "Firmware",
  info_brand: "Märke",
  info_led_dimmer_version: "Programversion för led-dimmer",
  info_production_date: "Tillverkningsdatum",
  info_serial_number: "Serienummer",
  info_software_date: "Programdatum",

  prop_resource_id: "Resurs-id:",
  badge_id_title: "IHC-resurs-id:t. Det är det som den manuella konfigurationen och IHC Visual pekar på.",
  prop_copy_title: "Kopiera resurs-id till urklipp",
  prop_type: "Typ:",
  prop_value: "Värde nu:",
  prop_value_title: "Värdet i ihc-styrenheten just nu. Knapparna bredvid skriver till styrenheten, så de slår av och på den riktiga utgången.",
  prop_entity: "Entitet:",
  sec_ihc: "I IHC",
  sec_hass: "I Home Assistant",
  sec_actions: "Åtgärder",
  prop_close: "Stäng",
  prop_display_name: "Namn i Home Assistant:",
  prop_display_name_title: "Namnet som Home Assistant visar. Det börjar gälla direkt - ingen omstart - och behålls när ihc-integrationen laddas om.",
  name_placeholder: "(namnet från ihc-konfigurationen)",
  not_in_hass: "Resursen är ännu inte en entitet i Home Assistant.",
  automatic_help: "Entiteten kommer från själva ihc-konfigurationen och inte från en manuell konfiguration, så det finns inget att ta bort här.",
  rename_edit_id: "Ändra entitets-id",
  rename_saved: "Sparat",
  rename_cancel: "Avbryt",
  rename_saving: "Sparar...",
  entity_id_warning: "Allt som pekar på det gamla entitets-id:t slutar fungera: automationer, skript, scener, instrumentpaneler, mallar - och allt utanför Home Assistant. Den här panelen kan inte säga vad det är. Det kan Home Assistants egen entitetsdialog under Inställningar, Enheter och tjänster, Entiteter.",
  rename_no_entity: "Det finns ingen entitet att byta namn på.",
  rename_not_in_registry: "Entiteten finns inte i Home Assistants entitetsregister och kan därför inte byta namn härifrån.",
  rename_not_ours: "Entiteten hör inte till den här ihc-styrenheten.",
  rename_id_invalid: "Det är inte ett giltigt entitets-id. Det ska vara domän.namn med små bokstäver och understreck i stället för mellanslag.",
  rename_id_domain: "Delen före punkten säger vilken sorts entitet det är, och den kan inte ändras genom namnbyte.",
  rename_id_taken: "Det entitets-id:t används redan.",
  rename_failed: "Namnbytet misslyckades - se Home Assistant-loggen",
  binary_sensor_help: "Sensorn är on medan knappen hålls nere och off när den släpps. En kort tryckning och släppet kan användas direkt som utlösare, och en lång tryckning är samma utlösare med en varaktighet. Ett dubbelklick måste byggas: den första tryckningen måste vänta och se om en till kommer, så varje enskild tryckning fördröjs lika länge som det fönstret varar.",
  prop_product: "Produkt:",
  prop_product_type: "Produkttyp:",
  prop_ihc_icon: "ikon {0}",
  prop_product_no_icon: "ingen egen ikon",
  pick_icon_title: "Välj en ikon för det här rummet",
  dlg_icon_title: "Ikon för {0}",
  dlg_icon_hint: "Vilken material-ikon som helst, till exempel mdi:sofa eller mdi:washing-machine. Ikonen bredvid fältet visar hur den ser ut. Valet sparas i Home Assistant, så rummen ser likadana ut i alla webbläsare.",
  dlg_icon_clear: "Standard",
  icon_save_failed: "Ikonen kunde inte sparas - se Home Assistant-loggen",
  value_on: "på",
  value_off: "av",
  value_toggle: "växla",
  value_on_title: "Sätt värdet till På (true)",
  value_off_title: "Sätt värdet till Av (false)",
  value_toggle_title: "Växla värdet",
  remove_manual: "Ta bort manuell konfiguration",
  manual_help: "Resursen är konfigurerad manuellt. Knappen ovan tar bort den från Home Assistant igen - tillsammans med dess område och etiketter.",
  pending_removal_help: "Den manuella konfigurationen har tagits bort. Entiteten finns kvar tills Home Assistant har läst om ihc-integrationen, men resurs-id:t är ledigt och kan läggas till igen direkt.",
  working_update: "Uppdaterar Home Assistant...",
  not_updated_yet: "Konfigurerad, men Home Assistant har inte uppdaterats än. Knappen högst upp försöker igen.",
  add_already_set_up: "Resursen är redan konfigurerad i Home Assistant.",
  change_failed: "Ändringen kunde inte göras - se Home Assistant-loggen",
  remove_dlg_title: "Ta bort från Home Assistant?",
  remove_dlg_text: "{0} tas bort från Home Assistant tillsammans med sitt område och sina etiketter. Läggs resursen till igen blir den en ny entitet.",
  remove_dlg_checking: "Letar efter vad som använder den...",
  remove_dlg_used: "Det här använder den och slutar fungera:",
  remove_dlg_unused: "Inga automationer, skript, scener, grupper eller instrumentpaneler använder den.",
  remove_dlg_not_checked: "Mallar och andra integrationer, till exempel Alarmo, är inte kontrollerade.",
  remove_dlg_lookup_failed: "Det gick inte att ta reda på vad som använder den.",
  remove_dlg_ok: "Ta bort",
  used_automation: "Automationer",
  used_script: "Skript",
  used_scene: "Scener",
  used_group: "Grupper",
  used_person: "Personer",
  used_dashboard: "Instrumentpaneler",
  add_binary_sensor_button: "Binär sensor",
  add_light_button: "Ljus",
  add_sensor_button: "Sensor",
  add_switch_button: "Brytare",
  add_help: "Klicka på en av knapparna för att konfigurera det här ihc-resurs-id:t som en entitet i Home Assistant. Observera: det är en manuell konfiguration och du bör veta vad du gör. Att något går att lägga till betyder inte att det är vettigt.",
  sec_add: "Lägg till i Home Assistant",
  not_in_hass_how: "Välj under »Lägg till i Home Assistant« vad den ska vara. Du får ange ett namn, och entitets-id:t byggs utifrån det.",
  add_binary_sensor_help: "En sensor som är on eller off. Rätt val för en knapp eller en kontakt: on medan den hålls nere, off när den släpps. Den bara läser.",
  add_light_help: "En lampa som kan slås av och på från Home Assistant - och dimmas, om resursen är en ljusnivå.",
  add_switch_help: "Något som kan slås av och på från Home Assistant. För en utgång som inte är en lampa: ett uttag, en siren, ett relä.",
  add_sensor_help: "Ett mätvärde - en siffra, en temperatur, en tid. Den bara läser.",
  add_writes_input: "Resursen är en ingång, så att slå på den skriver till styrenheten: den säger att knappen har tryckts.",

  dlg_binary_sensor_title: "Lägg till en binär sensor",
  dlg_light_title: "Lägg till ett ljus",
  dlg_switch_title: "Lägg till en brytare",
  dlg_sensor_title: "Lägg till en sensor",
  dlg_resource_id: "IHC-resurs-id: {0}",
  dlg_name: "Namn",
  dlg_entity_id_becomes: "Entitets-id: {0}",
  dlg_inverted: "Inverterad",
  dlg_type: "Typ",
  dlg_unit: "Måttenhet (valfritt)",
  dlg_ok: "Ok",
  dlg_cancel: "Avbryt",
  dlg_name_required: "Du måste ange ett namn",
};
